// <auto-generated />
using System;
using CarbonAware.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarbonAware.Api.Migrations
{
    [DbContext(typeof(LoggingDbContext))]
    [Migration("20260814083314_WidenModeColumn")]
    partial class WidenModeColumn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceCandidateLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("BestMoerAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("BestMoerUntilTarget")
                        .HasColumnType("float");

                    b.Property<string>("Cloud")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("CompositeScore")
                        .HasColumnType("float");

                    b.Property<bool?>("CostIsLive")
                        .HasColumnType("bit");

                    b.Property<string>("CostSource")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double?>("CostUsdPerHr")
                        .HasColumnType("float");

                    b.Property<bool?>("Excluded")
                        .HasColumnType("bit");

                    b.Property<string>("ExclusionReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("ExecutionId")
                        .HasColumnType("bigint");

                    b.Property<double?>("LatencyMs")
                        .HasColumnType("float");

                    b.Property<string>("LatencySource")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double?>("MoerAtTarget")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionId");

                    b.ToTable("AdviceCandidates");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceExecutionLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageCostUsdPerHr")
                        .HasColumnType("float");

                    b.Property<double?>("AverageEmissionGPerKwh")
                        .HasColumnType("float");

                    b.Property<double?>("AverageEstimatedSavingPercent")
                        .HasColumnType("float");

                    b.Property<double?>("AverageLatencyMs")
                        .HasColumnType("float");

                    b.Property<string>("BestWindowCloud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("BestWindowMoerGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("BestWindowRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("BestWindowWhen")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("CandidateCount")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("EstimatedSavingGPerKwh")
                        .HasColumnType("float");

                    b.Property<double?>("EstimatedSavingPercent")
                        .HasColumnType("float");

                    b.Property<string>("HighestCostCloud")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("HighestCostRegion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<double?>("HighestCostUsdPerHr")
                        .HasColumnType("float");

                    b.Property<string>("HighestEmissionCloud")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HighestEmissionGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("HighestEmissionRegion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HighestLatencyCloud")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("HighestLatencyMs")
                        .HasColumnType("float");

                    b.Property<string>("HighestLatencyRegion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ObjectiveType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PreferredCloudsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredRegionsCsv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<bool?>("RegionsDiffer")
                        .HasColumnType("bit");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SelectedCloud")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<double?>("SelectedCompositeScore")
                        .HasColumnType("float");

                    b.Property<double?>("SelectedCostUsdPerHr")
                        .HasColumnType("float");

                    b.Property<double?>("SelectedLatencyMs")
                        .HasColumnType("float");

                    b.Property<double?>("SelectedMoerGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("SelectedRegion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("SelectedWhen")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("SingleObjectiveCloud")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SingleObjectiveRegion")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset>("TargetWhen")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("WeightCarbon")
                        .HasColumnType("float");

                    b.Property<double?>("WeightCost")
                        .HasColumnType("float");

                    b.Property<double?>("WeightLatency")
                        .HasColumnType("float");

                    b.Property<string>("WeightProfile")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.ToTable("AdviceExecutions");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.CycleResultLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ActualCostSource")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<double?>("ActualCostUsdPerHr")
                        .HasColumnType("float");

                    b.Property<double?>("ActualMoerGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("ActualMoerSource")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("ActualTimestampEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ActualTimestampStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CloudProvider")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CycleId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<bool?>("DeploymentSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("ErrorNotes")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<double?>("ExecutionTimeSec")
                        .HasColumnType("float");

                    b.Property<double?>("LatencyActualSec")
                        .HasColumnType("float");

                    b.Property<string>("ObjectiveType")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("PredictedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("PredictedCostUsdPerHr")
                        .HasColumnType("float");

                    b.Property<double?>("PredictedLatencyMs")
                        .HasColumnType("float");

                    b.Property<double?>("PredictedMoerGPerKwh")
                        .HasColumnType("float");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("UpdatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("WeightConfig")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("CycleId", "CloudProvider", "Region")
                        .IsUnique();

                    b.ToTable("CycleResults");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.WattTimeCallLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DurationMs")
                        .HasColumnType("int");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HorizonHours")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("Region")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestUrl")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignalType")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("SourceFile")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int?>("SourceLine")
                        .HasColumnType("int");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<bool>("Success")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("WattTimeCalls");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceCandidateLog", b =>
                {
                    b.HasOne("CarbonAware.Api.Data.AdviceExecutionLog", "Execution")
                        .WithMany("Candidates")
                        .HasForeignKey("ExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Execution");
                });

            modelBuilder.Entity("CarbonAware.Api.Data.AdviceExecutionLog", b =>
                {
                    b.Navigation("Candidates");
                });
#pragma warning restore 612, 618
        }
    }
}
